import * as envir from "$env/static/public";

const env = envir as Record<string, string>;

const COUNTER_ADDRESS_BUILDNET = "AS1etQoQgUJUjuUsKLwmFNJQ4sDfrTg7Xm761Aw729E6ZbakJLDx";
const COUNTER_ADDRESS_MAINNET = "AS12b4pgVgvF9GKL6S8wZ6AEKENeqihZ8Qmxkr5NT4Ho7wYp9D9NT";
const COUNTER_ADDRESS = String(env.PUBLIC_COUNTER_ADDRESS || COUNTER_ADDRESS_MAINNET);

const BURNER_WALLET_KEY = String(env.PUBLIC_BURNER_WALLET_KEY || "");

export { COUNTER_ADDRESS, COUNTER_ADDRESS_MAINNET, COUNTER_ADDRESS_BUILDNET, BURNER_WALLET_KEY };
